// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeWoman.Infrastructure.Persistence;

#nullable disable

namespace SafeWoman.Infrastructure.Migrations
{
    [DbContext(typeof(SafeWomanDbContext))]
    [Migration("20260708211146_AgregarTablaArchivo")]
    partial class AgregarTablaArchivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeWoman.Domain.Entities.Administrador", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_admin");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdmin"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("IdAdmin");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_ADMINISTRADOR_email");

                    b.ToTable("ADMINISTRADOR", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.AlertaSos", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("activa")
                        .HasColumnName("estado");

                    b.Property<int>("IdVictima")
                        .HasColumnType("integer")
                        .HasColumnName("id_victima");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("latitud");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("longitud");

                    b.Property<DateTime>("TimestampActivacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_activacion")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime?>("TimestampCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_cancelacion");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdVictima", "Estado")
                        .HasDatabaseName("IX_ALERTA_SOS_victima_estado");

                    b.ToTable("ALERTA_SOS", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.ArchivoAlmacenado", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_archivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArchivo"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contenido");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_original");

                    b.Property<long>("Tamanio")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.HasKey("IdArchivo");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_ARCHIVO_categoria");

                    b.ToTable("ARCHIVO", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.ContactoEmergencia", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_contacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContacto"));

                    b.Property<int>("IdVictima")
                        .HasColumnType("integer")
                        .HasColumnName("id_victima");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("telefono");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdVictima");

                    b.ToTable("CONTACTO_EMERGENCIA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Denuncia", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDenuncia"));

                    b.Property<bool>("DeclaracionJurada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("declaracion_jurada");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateOnly?>("FechaHecho")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hecho");

                    b.Property<string>("FotoDniRuta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_dni_ruta");

                    b.Property<TimeOnly?>("HoraHecho")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_hecho");

                    b.Property<int>("IdVictima")
                        .HasColumnType("integer")
                        .HasColumnName("id_victima");

                    b.Property<decimal?>("LatHecho")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("lat_hecho");

                    b.Property<decimal?>("LngHecho")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("lng_hecho");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provincia");

                    b.Property<string>("ReferenciaUbicacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referencia_ubicacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdDenuncia");

                    b.HasIndex("IdVictima")
                        .HasDatabaseName("IX_DENUNCIA_victima");

                    b.HasIndex("Estado", "Tipo", "FechaEnvio")
                        .HasDatabaseName("IX_DENUNCIA_estado_tipo_fecha");

                    b.ToTable("DENUNCIA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.DenunciaAnonima", b =>
                {
                    b.Property<int>("IdDenunciaAnonima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia_anonima");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDenunciaAnonima"));

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateOnly?>("FechaHecho")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hecho");

                    b.Property<TimeOnly?>("HoraHecho")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_hecho");

                    b.Property<int>("IdHuella")
                        .HasColumnType("integer")
                        .HasColumnName("id_huella");

                    b.Property<decimal?>("LatHecho")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("lat_hecho");

                    b.Property<decimal?>("LngHecho")
                        .HasColumnType("DECIMAL(10,7)")
                        .HasColumnName("lng_hecho");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provincia");

                    b.Property<string>("ReferenciaUbicacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referencia_ubicacion");

                    b.HasKey("IdDenunciaAnonima");

                    b.HasIndex("IdHuella")
                        .HasDatabaseName("IX_DENUNCIA_ANONIMA_huella");

                    b.HasIndex("Estado", "FechaEnvio")
                        .HasDatabaseName("IX_DENUNCIA_ANONIMA_estado_fecha");

                    b.ToTable("DENUNCIA_ANONIMA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Denunciado", b =>
                {
                    b.Property<int>("IdDenunciado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_denunciado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDenunciado"));

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia");

                    b.Property<string>("NombreAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_alias");

                    b.Property<string>("RelacionVictima")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion_victima");

                    b.HasKey("IdDenunciado");

                    b.HasIndex("IdDenuncia")
                        .IsUnique();

                    b.ToTable("DENUNCIADO", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.DenunciadoAnonima", b =>
                {
                    b.Property<int>("IdDenunciadoAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_denunciado_an");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDenunciadoAn"));

                    b.Property<int>("IdDenunciaAnonima")
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia_anonima");

                    b.Property<string>("NombreAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_alias");

                    b.Property<string>("Relacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion");

                    b.HasKey("IdDenunciadoAn");

                    b.HasIndex("IdDenunciaAnonima")
                        .IsUnique();

                    b.ToTable("DENUNCIADO_ANONIMA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Evidencia", b =>
                {
                    b.Property<int>("IdEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_evidencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvidencia"));

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("imagen")
                        .HasColumnName("tipo_archivo");

                    b.HasKey("IdEvidencia");

                    b.HasIndex("IdDenuncia");

                    b.ToTable("EVIDENCIA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.EvidenciaAnonima", b =>
                {
                    b.Property<int>("IdEvidenciaAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_evidencia_an");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvidenciaAn"));

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<int>("IdDenunciaAnonima")
                        .HasColumnType("integer")
                        .HasColumnName("id_denuncia_anonima");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("imagen")
                        .HasColumnName("tipo_archivo");

                    b.HasKey("IdEvidenciaAn");

                    b.HasIndex("IdDenunciaAnonima");

                    b.ToTable("EVIDENCIA_ANONIMA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.HuellaDispositivo", b =>
                {
                    b.Property<int>("IdHuella")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_huella");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHuella"));

                    b.Property<bool>("Bloqueada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bloqueada");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_fingerprint");

                    b.Property<DateTime>("FechaPrimerUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_primer_uso")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime>("FechaUltimoUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_uso")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.HasKey("IdHuella");

                    b.HasIndex("Bloqueada")
                        .HasDatabaseName("IX_HUELLA_bloqueada");

                    b.HasIndex("DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UQ_HUELLA_fingerprint");

                    b.ToTable("HUELLA_DISPOSITIVO", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entidad_afectada");

                    b.Property<int?>("IdAdmin")
                        .HasColumnType("integer")
                        .HasColumnName("id_admin");

                    b.Property<int?>("IdEntidadAfectada")
                        .HasColumnType("integer")
                        .HasColumnName("id_entidad_afectada");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.HasKey("IdLog");

                    b.HasIndex("IdAdmin", "Timestamp")
                        .HasDatabaseName("IX_LOG_admin_timestamp");

                    b.ToTable("LOG_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.OtpVerificacion", b =>
                {
                    b.Property<int>("IdOtp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_otp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOtp"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("CHAR(6)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<int>("IdVictima")
                        .HasColumnType("integer")
                        .HasColumnName("id_victima");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("usado");

                    b.HasKey("IdOtp");

                    b.HasIndex("IdVictima", "Usado", "FechaExpiracion")
                        .HasDatabaseName("IX_OTP_victima_usado");

                    b.ToTable("OTP_VERIFICACION", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Victima", b =>
                {
                    b.Property<int>("IdVictima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_victima");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVictima"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("dni");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("telefono");

                    b.Property<bool>("Verificada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verificada");

                    b.HasKey("IdVictima");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("UQ_VICTIMA_dni");

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasDatabaseName("UQ_VICTIMA_telefono");

                    b.ToTable("VICTIMA", (string)null);
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.AlertaSos", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Victima", "Victima")
                        .WithMany("AlertasSos")
                        .HasForeignKey("IdVictima")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Victima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.ContactoEmergencia", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Victima", "Victima")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("IdVictima")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Victima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Denuncia", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Victima", "Victima")
                        .WithMany("Denuncias")
                        .HasForeignKey("IdVictima")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Victima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.DenunciaAnonima", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.HuellaDispositivo", "HuellaDispositivo")
                        .WithMany()
                        .HasForeignKey("IdHuella")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HuellaDispositivo");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Denunciado", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Denuncia", "Denuncia")
                        .WithOne("Denunciado")
                        .HasForeignKey("SafeWoman.Domain.Entities.Denunciado", "IdDenuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.DenunciadoAnonima", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.DenunciaAnonima", "DenunciaAnonima")
                        .WithOne("Denunciado")
                        .HasForeignKey("SafeWoman.Domain.Entities.DenunciadoAnonima", "IdDenunciaAnonima")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DenunciaAnonima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Denuncia", "Denuncia")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdDenuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.EvidenciaAnonima", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.DenunciaAnonima", "DenunciaAnonima")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdDenunciaAnonima")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DenunciaAnonima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("IdAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.OtpVerificacion", b =>
                {
                    b.HasOne("SafeWoman.Domain.Entities.Victima", "Victima")
                        .WithMany()
                        .HasForeignKey("IdVictima")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Victima");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Denuncia", b =>
                {
                    b.Navigation("Denunciado");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.DenunciaAnonima", b =>
                {
                    b.Navigation("Denunciado");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("SafeWoman.Domain.Entities.Victima", b =>
                {
                    b.Navigation("AlertasSos");

                    b.Navigation("ContactosEmergencia");

                    b.Navigation("Denuncias");
                });
#pragma warning restore 612, 618
        }
    }
}
